version: "3.9"
services:

  db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - default

  etl: 
    build: 
      context: .
      dockerfile: .Dockerfile
    environment:
      - DATABASE=mongodb://db:27017
    command: python run_etl.py
    networks:
      - default


networks:
  default:
    name: model
